#!/usr/bin/env python3

import colors as c

print(c.green + 'MASTER CHIEF FOR LIVE BRA!!!')

print(c.cyan + 'Hello and to whoever the heck is reading this! If you play Halo, than you can do this quiz!')
print(c.green + 'If not, then your gonna fail! :)')







