#!/usr/bin/env python3

import colors as c

c.clear_screen()
print(c.yellow + "Hi, what's your name?" + c.reset)
name = input('-->' + c.orange)
print(c.red + 'Well' + c.magenta + name + c.red + 'Nice to meet you,' + name + '!')














